configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
 - Pages
 - Numbers
 - Keynote
 - News
 - Music
 - Reminders
 - Contacts
 - FaceTime
 - Photos
 - Maps

dockitems_persist: 
 - name: "stoic"
   path: "/Applications/stoic.app"
   pos: 1
 - name: "Things3"
   path: "/Applications/Things3.app"
   pos: 2
 - name: "Obsidian"
   path: "/Applications/Obsidian.app"
   pos: 3
 - name: "Sublime Text"
   path: "/Applications/Sublime Text.app/"
   pos: 5


dotfiles_repo: https://github.com/ebfio/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/code/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  #- doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  #- httpie
  - iperf
  - libevent
  - sqlite
  #- mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - rust
 
homebrew_cask_apps:
  - chromedriver
  #- bitwarden
  - sqlpro-for-sqlite
  - docker
  - dropbox
  - firefox
  - warp
  - arq
  - google-chrome
  - handbrake
  - licecap
  - appcleaner
  - barrier
  - coconutBattery
  - spotify
  - sonos
  - bambu-studio
  - steam
  - raspberry-pi-imager
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - alfred
  - adobe-creative-cloud
  - anaconda
  - vlc
  - obs
  - obs-virtualcam
  - whatsapp
  - zoom
  - utm
  - pycharm-ce
  - markright
  - iterm2
  - obsidian
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - 1502839586 # Handmirror
  - 1352778147 # Bitwarden
  - 1312926037
  - 497799835 # XCode
  - 1502839586
  - 549083868
  - 1295203466 # Microsoft Remote Desktop
  - 6444602274 # Ivory
  - 904280696 # Things 3
  - 1147396723 # WhatsApp Desktop
  - 803453959 # Slack
  - 1451685025 # Wireguard
  - 1455214828 # MQTT Explorer
  - 1099568401 # Home Assistant

mas_email: ""
mas_password: ""

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
